// screen-timeline.jsx — Refined "Crawl Timeline" screen for the CrawlDirector DM console.
// Reuses tokens + Icon/SourceBadge/StatusPill from console-common.jsx and PROV/CAMPAIGN from console-data.jsx.
// Design intent: the timeline IS the descent. A floor-rail (the dungeon, 1→18) on the left;
// the main column is a vertical broadcast spine banded by floor, newest first, with provenance
// woven into every node and causality drawn as connective thread.

const { useState: useTL, useRef: useTLRef, useEffect: useTLEffect } = React;

/* entity-type → category color (mirrors console-data NODE_TYPE_COLOR) */
const TYPE_COLOR = {
  CRAWLER: "var(--accent)", NPC: "var(--ink)", SYSTEM_AI: "var(--ai)",
  ORGANIZATION: "var(--sys)", FACTION: "var(--hot)", FLOOR: "var(--ok)", LOCATION: "var(--import)",
};
function TypeDot({ type, size = 7 }) {
  return <span style={{ width: size, height: size, borderRadius: "50%", flexShrink: 0,
    background: TYPE_COLOR[type] || "var(--ink-dim)", display: "inline-block" }} />;
}

/* provenance accent for a source key */
const SRC_COLOR = { DM: "var(--ink-dim)", AI: "var(--ai)", PLAYER: "var(--player)", IMPORT: "var(--import)" };

/* ============================ SAMPLE CANON ============================ */
// Grounded in The Borant Broadcast (console-data.jsx). Newest first within each floor.
// Effects use the v1 contract: ADJUST_STAT on a crawler stat (gold/level/killCount).
const FLOORS = [
  {
    n: 9, name: "Larracos", theme: "Castle siege · the moat runs red",
    days: "Day 388 – 412", current: true,
    events: [
      {
        id: "e-911", day: "Day 412", time: "0600", source: "AI", live: true,
        title: "Siege timer enters its final 72 hours",
        summary: "The System opens the broadcast day by ratcheting the Floor-9 collapse clock. Safe-room access on the east wall is formally revoked.",
        secret: false, locked: false,
        participants: [
          { id: "ent-system", name: "The System", type: "SYSTEM_AI", role: "ACTOR" },
          { id: "ent-carl", name: "Carl", type: "CRAWLER", role: "WITNESS" },
          { id: "ent-donut", name: "Princess Donut", type: "CRAWLER", role: "WITNESS" },
        ],
        causedBy: [{ title: "The Barbican Falls" }],
        causes: [],
        effects: [],
      },
      {
        id: "e-910", day: "Day 411", time: "2240", source: "AI",
        title: "The Barbican Falls",
        summary: "The Grull Legion takes the eastern barbican after a night assault. Warboss Heg plants his standard on the breached wall as the audience picks sides.",
        secret: false, locked: true,
        participants: [
          { id: "ent-grull", name: "The Grull Legion", type: "FACTION", role: "ACTOR" },
          { id: "ent-skull", name: "Skull Empire", type: "FACTION", role: "AFFECTED" },
          { id: "ent-carl", name: "Carl", type: "CRAWLER", role: "WITNESS" },
          { id: "ent-larracos", name: "Larracos", type: "LOCATION", role: "LOCATION" },
        ],
        causedBy: [{ title: "Warboss Heg's Gambit" }],
        causes: [{ title: "Siege timer enters its final 72 hours" }],
        effects: [
          { target: "The Grull Legion", stat: "standing", delta: 9 },
          { target: "Skull Empire", stat: "standing", delta: -6 },
        ],
      },
      {
        id: "e-909", day: "Day 411", time: "1815", source: "PLAYER",
        title: "Donut's parapet taunt goes network-wide",
        summary: "Player ‘mattd' staged a monologue from the parapet mid-siege. The clip out-rated the war itself and a grateful sponsor wired a gift.",
        secret: false, locked: false,
        participants: [
          { id: "ent-donut", name: "Princess Donut", type: "CRAWLER", role: "ACTOR" },
          { id: "ent-heg", name: "Warboss Heg", type: "NPC", role: "TARGET" },
        ],
        causedBy: [],
        causes: [{ title: "Sponsor gift wired to Donut" }],
        effects: [
          { target: "Princess Donut", stat: "gold", delta: 12000 },
          { target: "Princess Donut", stat: "killCount", delta: 0, note: "fame +0.7M" },
        ],
      },
      {
        id: "e-908", day: "Day 410", time: "0300", source: "AI",
        title: "Warboss Heg's gambit",
        summary: "Heg commits his reserves to a pre-dawn moat crossing — a costly bet generated by the Encounter engine under persona S-07.",
        secret: false, locked: false,
        participants: [
          { id: "ent-grull", name: "The Grull Legion", type: "FACTION", role: "ACTOR" },
          { id: "ent-heg", name: "Warboss Heg", type: "NPC", role: "ACTOR" },
        ],
        causedBy: [],
        causes: [{ title: "The Barbican Falls" }],
        effects: [{ target: "Warboss Heg", stat: "status", delta: 0, note: "→ wounded" }],
      },
      {
        id: "e-907", day: "Day 388", time: "—", source: "AI",
        title: "The System awakens — Persona S-07",
        summary: "Snapshot ‘Petty God, Newly Awake' goes live. The System begins bending its own rulebook for the bit. DM-only until you choose to surface it.",
        secret: true, locked: false,
        participants: [
          { id: "ent-system", name: "The System", type: "SYSTEM_AI", role: "ACTOR" },
          { id: "ent-borant", name: "Borant Syndicate", type: "ORGANIZATION", role: "AFFECTED" },
        ],
        causedBy: [{ title: "Syndicate overturns the loot ruling" }],
        causes: [],
        effects: [],
      },
    ],
  },
  {
    n: 8, name: "The Bone Market", theme: "Black bazaar · everything has a price",
    days: "Day 300 – 360", current: false,
    events: [
      {
        id: "e-803", day: "Day 352", time: "1130", source: "IMPORT",
        title: "Syndicate overturns the loot ruling",
        summary: "Imported from the shared DCC core: Borant's board reverses the System's Floor-8 reward ruling. The System takes it personally.",
        secret: false, locked: false,
        participants: [
          { id: "ent-borant", name: "Borant Syndicate", type: "ORGANIZATION", role: "ACTOR" },
          { id: "ent-system", name: "The System", type: "SYSTEM_AI", role: "AFFECTED" },
        ],
        causedBy: [],
        causes: [{ title: "The System awakens — Persona S-07" }],
        effects: [],
      },
      {
        id: "e-802", day: "Day 331", time: "0900", source: "DM",
        title: "Mordecai signs on as guide",
        summary: "You logged the contract: an exiled Daghan named Mordecai takes Carl & Donut as clients. Quietly the most consequential handshake of the season.",
        secret: false, locked: true,
        participants: [
          { id: "ent-mordecai", name: "Mordecai", type: "NPC", role: "ACTOR" },
          { id: "ent-carl", name: "Carl", type: "CRAWLER", role: "AFFECTED" },
          { id: "ent-donut", name: "Princess Donut", type: "CRAWLER", role: "AFFECTED" },
        ],
        causedBy: [],
        causes: [],
        effects: [],
      },
      {
        id: "e-801", day: "Day 309", time: "1700", source: "DM",
        title: "Carl loses his pants (again)",
        summary: "Logged for continuity. The audience has decided this is a recurring bit. Carl has stopped fighting it.",
        secret: false, locked: false,
        participants: [{ id: "ent-carl", name: "Carl", type: "CRAWLER", role: "ACTOR" }],
        causedBy: [],
        causes: [],
        effects: [],
      },
    ],
  },
  {
    n: 7, name: "The Iron Choir", theme: "Resonant halls · the walls sing back",
    days: "Day 240 – 290", current: false,
    events: [
      {
        id: "e-702", day: "Day 277", time: "2015", source: "DM",
        title: "Princess Donut crosses 1M fame",
        summary: "The milestone that turned a murder-cat into a network draw. Marked canon and locked as a season landmark.",
        secret: false, locked: true,
        participants: [
          { id: "ent-donut", name: "Princess Donut", type: "CRAWLER", role: "ACTOR" },
          { id: "ent-maestro", name: "The Maestro", type: "NPC", role: "WITNESS" },
        ],
        causedBy: [],
        causes: [],
        effects: [{ target: "Princess Donut", stat: "level", delta: 2 }],
      },
      {
        id: "e-701", day: "Day 251", time: "0440", source: "AI",
        title: "Skull Empire crowns a rival warlord",
        summary: "Generated faction beat: the Skull Empire elevates a challenger to Heg, seeding the war that will define Floor 9.",
        secret: false, locked: false,
        participants: [
          { id: "ent-skull", name: "Skull Empire", type: "FACTION", role: "ACTOR" },
          { id: "ent-grull", name: "The Grull Legion", type: "FACTION", role: "AFFECTED" },
        ],
        causedBy: [],
        causes: [{ title: "Warboss Heg's gambit" }],
        effects: [],
      },
    ],
  },
];

const TIMELINE_FILTERS = ["ALL", "DM", "AI", "PLAYER", "IMPORT"];
const ALL_EVENTS = FLOORS.flatMap((f) => f.events);

/* the dungeon ladder shown in the left rail: 1 (surface) → 18 (deepest) */
const LADDER = Array.from({ length: 18 }, (_, i) => {
  const n = i + 1;
  const floor = FLOORS.find((f) => f.n === n);
  return { n, name: floor ? floor.name : null, count: floor ? floor.events.length : 0,
    current: n === 9, reached: n <= 9, logged: !!floor };
});

/* ============================ small parts ============================ */
function Chip({ children, color = "var(--ink-faint)", border = "var(--line-strong)", bg = "transparent", style }) {
  return <span style={{ fontFamily: "var(--font-mono)", fontSize: 9.5, letterSpacing: ".1em",
    textTransform: "uppercase", padding: "2px 6px", color, border: `1px solid ${border}`,
    background: bg, whiteSpace: "nowrap", display: "inline-flex", alignItems: "center", gap: 5, ...style }}>{children}</span>;
}

/* causality thread — the connective tissue between events */
function Thread({ dir, items }) {
  const inbound = dir === "in";
  return (
    <div style={{ display: "flex", alignItems: "flex-start", gap: 8, marginTop: 6 }}>
      <span style={{ fontFamily: "var(--font-mono)", fontSize: 9.5, letterSpacing: ".1em",
        textTransform: "uppercase", color: inbound ? "var(--ink-faint)" : "var(--accent)",
        flexShrink: 0, paddingTop: 1, display: "inline-flex", alignItems: "center", gap: 5 }}>
        <span style={{ fontSize: 13, lineHeight: 1, transform: inbound ? "scaleX(-1)" : "none", display: "inline-block" }}>{inbound ? "\u21B3" : "\u21B3"}</span>
        {inbound ? "Caused by" : "Causes"}
      </span>
      <div style={{ display: "flex", flexWrap: "wrap", gap: "4px 10px" }}>
        {items.map((it, i) => (
          <span key={i} style={{ fontSize: 12, color: "var(--ink-dim)", borderBottom: "1px dotted var(--line-strong)", cursor: "pointer" }}>{it.title}</span>
        ))}
      </div>
    </div>
  );
}

/* an effect rendered as a signed diff (broadcast HUD: glanceable stat deltas) */
function EffectChip({ e }) {
  const positive = e.delta > 0;
  const isDelta = typeof e.delta === "number" && e.delta !== 0;
  const valColor = e.note ? "var(--ink-dim)" : positive ? "var(--add)" : "var(--del)";
  const sign = positive ? "+" : "";
  const val = e.note ? e.note : `${sign}${e.stat === "gold" ? e.delta.toLocaleString() : e.delta}`;
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 7, fontFamily: "var(--font-mono)",
      fontSize: 11, padding: "3px 8px", border: "1px solid var(--line)", background: "var(--bg-2)", whiteSpace: "nowrap", flexShrink: 0 }}>
      <span style={{ color: "var(--ink-dim)" }}>{e.target}</span>
      <span style={{ color: "var(--ink-faint)" }}>{e.stat}</span>
      <span style={{ color: valColor, fontWeight: 600 }}>{val}</span>
    </span>
  );
}

/* ============================ event card ============================ */
function EventNode({ ev }) {
  const src = SRC_COLOR[ev.source] || "var(--ink-dim)";
  const [hover, setHover] = useTL(false);
  return (
    <article className="fade-in" style={{ position: "relative", paddingLeft: 40, paddingBottom: 22 }}
      onMouseEnter={() => setHover(true)} onMouseLeave={() => setHover(false)}>
      {/* spine node, colored by provenance */}
      <span aria-hidden style={{ position: "absolute", left: 13, top: 4, width: 13, height: 13,
        transform: "translateX(-50%)", borderRadius: "50%", background: "var(--bg)",
        border: `2px solid ${src}`,
        boxShadow: ev.live ? "0 0 0 4px color-mix(in srgb, var(--hot) 22%, transparent)" : (hover ? `0 0 0 4px color-mix(in srgb, ${src} 18%, transparent)` : "none"),
        transition: "box-shadow .15s" }}>
        {ev.secret && <span style={{ position: "absolute", inset: 2, borderRadius: "50%", border: "1px solid var(--bg-1)" }} />}
      </span>

      <div className="panel bracket" style={{ padding: "12px 15px 13px", borderColor: hover ? "var(--line-strong)" : "var(--line)",
        background: ev.live ? "color-mix(in srgb, var(--hot) 4%, var(--bg-1))" : "var(--bg-1)", transition: "border-color .15s" }}>
        {/* meta row */}
        <div style={{ display: "flex", alignItems: "center", gap: 9, flexWrap: "wrap", marginBottom: 8 }}>
          {ev.live && <span style={{ display: "inline-flex", alignItems: "center", gap: 6, color: "var(--hot)",
            fontFamily: "var(--font-mono)", fontSize: 9.5, letterSpacing: ".14em", textTransform: "uppercase" }}>
            <span className="live-dot" />Now</span>}
          <span style={{ fontFamily: "var(--font-mono)", fontSize: 10.5, letterSpacing: ".04em", color: "var(--ink-dim)" }}>
            {ev.day}{ev.time !== "—" && <span style={{ color: "var(--ink-faint)" }}> · {ev.time}</span>}
          </span>
          <SourceBadge source={ev.source} small />
          {ev.secret && <Chip color="var(--hot)" border="color-mix(in srgb, var(--hot) 45%, transparent)" bg="color-mix(in srgb, var(--hot) 8%, transparent)">
            <Icon name="eyeOff" size={11} />DM-only</Chip>}
          {ev.locked && <Chip color="var(--sys)" border="color-mix(in srgb, var(--sys) 45%, transparent)"><Icon name="lock" size={10} />Locked</Chip>}
          <span style={{ marginLeft: "auto", display: "inline-flex", alignItems: "center", gap: 6 }}>
            <button title="Edit event" style={iconBtn(hover)}><Icon name="edit" size={12} /></button>
          </span>
        </div>

        {/* title */}
        <h3 style={{ margin: 0, fontFamily: "var(--font-display)", fontSize: 16.5, fontWeight: 600,
          letterSpacing: ".005em", lineHeight: 1.25, color: "var(--ink)" }}>{ev.title}</h3>

        {/* summary */}
        {ev.summary && <p style={{ margin: "6px 0 0", fontSize: 12.5, lineHeight: 1.55, color: "var(--ink-dim)", maxWidth: 660 }}>{ev.summary}</p>}

        {/* participants */}
        {ev.participants.length > 0 && (
          <div style={{ marginTop: 11, display: "flex", flexWrap: "wrap", gap: "6px 7px" }}>
            {ev.participants.map((p) => (
              <span key={p.id + p.role} title={`${p.name} · ${p.role}`} style={{ display: "inline-flex", alignItems: "center", gap: 6,
                padding: "3px 8px 3px 7px", border: "1px solid var(--line)", background: "var(--bg-2)", fontSize: 11.5, color: "var(--ink-dim)", cursor: "pointer" }}>
                <TypeDot type={p.type} />
                <span style={{ color: "var(--ink)" }}>{p.name}</span>
                <span style={{ fontFamily: "var(--font-mono)", fontSize: 8.5, letterSpacing: ".08em", color: "var(--ink-faint)" }}>{p.role}</span>
              </span>
            ))}
          </div>
        )}

        {/* causality threads */}
        {(ev.causedBy.length > 0 || ev.causes.length > 0) && (
          <div style={{ marginTop: 11, paddingTop: 10, borderTop: "1px solid var(--line)" }}>
            {ev.causedBy.length > 0 && <Thread dir="in" items={ev.causedBy} />}
            {ev.causes.length > 0 && <Thread dir="out" items={ev.causes} />}
          </div>
        )}

        {/* effects */}
        {ev.effects.length > 0 && (
          <div style={{ marginTop: 11, paddingTop: 10, borderTop: "1px solid var(--line)" }}>
            <div style={{ fontFamily: "var(--font-mono)", fontSize: 9, letterSpacing: ".12em", textTransform: "uppercase",
              color: "var(--ink-faint)", marginBottom: 7, display: "flex", alignItems: "center", gap: 7 }}>
              <Icon name="bolt" size={11} style={{ color: "var(--accent)" }} />Effects on canon
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 7, alignItems: "center" }}>
              {ev.effects.map((e, i) => <EffectChip key={i} e={e} />)}
              <button style={{ ...iconBtn(true), fontFamily: "var(--font-mono)", fontSize: 9.5, letterSpacing: ".08em",
                textTransform: "uppercase", padding: "4px 9px", width: "auto", height: "auto", color: "var(--ok)", borderColor: "color-mix(in srgb, var(--ok) 45%, transparent)" }}>
                <Icon name="check" size={12} />Apply</button>
            </div>
          </div>
        )}
      </div>
    </article>
  );
}
function iconBtn(active) {
  return { width: 26, height: 26, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 5,
    background: "transparent", border: "1px solid var(--line)", color: active ? "var(--ink-dim)" : "var(--ink-faint)",
    cursor: "pointer", opacity: active ? 1 : 0.55, transition: "opacity .15s, color .15s" };
}

/* ============================ floor band ============================ */
function FloorBand({ floor }) {
  return (
    <section style={{ position: "relative" }}>
      {/* spine for this band */}
      <div aria-hidden style={{ position: "absolute", left: 13, top: 26, bottom: 0, width: 1,
        background: floor.current ? "color-mix(in srgb, var(--accent) 35%, var(--line-strong))" : "var(--line-strong)" }} />

      {/* floor header */}
      <header style={{ position: "relative", paddingLeft: 40, marginBottom: 16 }}>
        <span aria-hidden style={{ position: "absolute", left: 13, top: 5, width: 17, height: 17, transform: "translateX(-50%)",
          border: `1.5px solid ${floor.current ? "var(--accent)" : "var(--ink-faint)"}`, background: "var(--bg)",
          display: "grid", placeItems: "center" }}>
          <span style={{ width: 5, height: 5, background: floor.current ? "var(--accent)" : "var(--ink-faint)" }} />
        </span>
        <div style={{ display: "flex", alignItems: "baseline", gap: 14, flexWrap: "wrap" }}>
          <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, letterSpacing: ".22em", whiteSpace: "nowrap", color: floor.current ? "var(--accent)" : "var(--ink-faint)" }}>
            FLOOR {String(floor.n).padStart(2, "0")}
          </span>
          <h2 style={{ margin: 0, fontFamily: "var(--font-display)", fontSize: 21, fontWeight: 700, letterSpacing: ".01em",
            color: "var(--ink)", textTransform: "uppercase" }}>{floor.name}</h2>
          {floor.current && <span style={{ display: "inline-flex", alignItems: "center", gap: 6, color: "var(--hot)", whiteSpace: "nowrap",
            fontFamily: "var(--font-mono)", fontSize: 9.5, letterSpacing: ".14em", textTransform: "uppercase" }}><span className="live-dot" />On air</span>}
        </div>
        <div style={{ marginTop: 5, display: "flex", gap: 14, flexWrap: "wrap", fontFamily: "var(--font-mono)", fontSize: 10.5, color: "var(--ink-faint)" }}>
          <span style={{ color: "var(--ink-dim)" }}>{floor.theme}</span>
          <span>{floor.days}</span>
          <span>{floor.events.length} {floor.events.length === 1 ? "event" : "events"}</span>
        </div>
      </header>

      <div>{floor.events.map((ev) => <EventNode key={ev.id} ev={ev} />)}</div>
    </section>
  );
}

/* ============================ left rail: the descent ============================ */
function FloorRail({ filter, setFilter }) {
  return (
    <aside style={{ borderRight: "1px solid var(--line)", background: "var(--bg-1)", display: "flex", flexDirection: "column", minHeight: 0 }}>
      <div style={{ padding: "16px 16px 14px", borderBottom: "1px solid var(--line)" }}>
        <div className="kicker" style={{ marginBottom: 9 }}>The Descent</div>
        <div style={{ fontFamily: "var(--font-display)", fontSize: 15, fontWeight: 600, color: "var(--ink)" }}>{CAMPAIGN.name}</div>
        <div style={{ marginTop: 5, fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--ink-faint)" }}>
          {ALL_EVENTS.length} events logged · canon v118
        </div>
      </div>

      {/* dungeon ladder */}
      <div style={{ overflowY: "auto", flex: 1, padding: "10px 10px 16px" }}>
        <div style={{ fontFamily: "var(--font-mono)", fontSize: 9, letterSpacing: ".18em", textTransform: "uppercase",
          color: "var(--ink-faint)", padding: "4px 6px 8px" }}>Floors 01 — 18</div>
        <div style={{ position: "relative" }}>
          <div aria-hidden style={{ position: "absolute", left: 17, top: 8, bottom: 8, width: 1, background: "var(--line)" }} />
          {LADDER.map((f) => {
            const active = f.current;
            return (
              <button key={f.n} title={f.name ? `Floor ${f.n} — ${f.name}` : `Floor ${f.n} · not yet reached`} style={{
                position: "relative", display: "grid", gridTemplateColumns: "24px 1fr auto", alignItems: "center", gap: 9,
                width: "100%", textAlign: "left", padding: "6px 8px", background: active ? "var(--bg-3)" : "transparent",
                border: "none", borderLeft: `2px solid ${active ? "var(--accent)" : "transparent"}`, cursor: "pointer",
                opacity: f.reached ? 1 : 0.4 }}>
                <span style={{ position: "relative", display: "grid", placeItems: "center" }}>
                  <span style={{ width: 9, height: 9, borderRadius: "50%", background: "var(--bg-1)",
                    border: `2px solid ${active ? "var(--accent)" : f.logged ? "var(--ink-dim)" : f.reached ? "var(--ink-faint)" : "var(--line-strong)"}`,
                    zIndex: 1 }} />
                </span>
                <span style={{ minWidth: 0 }}>
                  <span style={{ fontFamily: "var(--font-mono)", fontSize: 11, color: active ? "var(--accent)" : f.reached ? "var(--ink-dim)" : "var(--ink-faint)" }}>
                    F{String(f.n).padStart(2, "0")}
                  </span>
                  {f.name && <span style={{ marginLeft: 8, fontSize: 11.5, color: active ? "var(--ink)" : "var(--ink-dim)",
                    whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{f.name}</span>}
                </span>
                {f.logged ? <span style={{ fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--ink-faint)" }}>{f.count}</span>
                  : active ? null : <Icon name="lock" size={10} style={{ color: "var(--line-strong)" }} />}
              </button>
            );
          })}
        </div>
      </div>

      {/* provenance filter */}
      <div style={{ padding: "13px 14px 15px", borderTop: "1px solid var(--line)" }}>
        <div style={{ fontFamily: "var(--font-mono)", fontSize: 9, letterSpacing: ".18em", textTransform: "uppercase",
          color: "var(--ink-faint)", marginBottom: 9 }}>Filter by origin</div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 5 }}>
          {TIMELINE_FILTERS.map((f) => {
            const on = filter === f;
            const c = f === "ALL" ? "var(--accent)" : SRC_COLOR[f];
            return (
              <button key={f} onClick={() => setFilter(f)} style={{ fontFamily: "var(--font-mono)", fontSize: 10,
                letterSpacing: ".08em", padding: "4px 9px", textTransform: "uppercase",
                background: on ? (f === "ALL" ? "var(--accent)" : `color-mix(in srgb, ${c} 16%, transparent)`) : "transparent",
                color: on ? (f === "ALL" ? "var(--accent-ink)" : c) : "var(--ink-dim)",
                border: `1px solid ${on ? c : "var(--line-strong)"}` }}>{f === "PLAYER" ? "PLR" : f === "IMPORT" ? "IMP" : f}</button>
            );
          })}
        </div>
      </div>
    </aside>
  );
}

/* ============================ the screen ============================ */
function TimelineScreen() {
  const [filter, setFilter] = useTL("ALL");
  const scrollRef = useTLRef(null);

  const floors = FLOORS.map((f) => ({
    ...f,
    events: filter === "ALL" ? f.events : f.events.filter((e) => e.source === filter),
  })).filter((f) => f.events.length > 0);

  const shown = floors.reduce((n, f) => n + f.events.length, 0);

  return (
    <div style={{ display: "grid", gridTemplateColumns: "264px minmax(0,1fr)", height: "100%", minHeight: 0 }}>
      <FloorRail filter={filter} setFilter={setFilter} />

      {/* main timeline column */}
      <div style={{ display: "flex", flexDirection: "column", minHeight: 0 }}>
        {/* header */}
        <div className="bracket" style={{ padding: "18px 26px 16px", borderBottom: "1px solid var(--line)", background: "var(--bg-1)" }}>
          <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 18, flexWrap: "wrap" }}>
            <div>
              <div className="kicker" style={{ marginBottom: 8, whiteSpace: "nowrap" }}>Timeline · most recent first</div>
              <h1 style={{ margin: 0, fontFamily: "var(--font-display)", fontSize: 27, fontWeight: 700, letterSpacing: ".01em" }}>Crawl Timeline</h1>
            </div>
            <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}>
              <span className="hud-tag"><span className="live-dot" />Floor 9 · Day 412</span>
              <span className="hud-tag">{shown} / {ALL_EVENTS.length} shown</span>
              <button style={{ display: "inline-flex", alignItems: "center", gap: 7, padding: "8px 13px", fontFamily: "var(--font-mono)",
                fontSize: 11, letterSpacing: ".06em", textTransform: "uppercase", background: "var(--accent)", color: "var(--accent-ink)",
                border: "1px solid var(--accent)" }}><Icon name="plus" size={14} />Log event</button>
            </div>
          </div>
        </div>

        {/* scrollable spine */}
        <div ref={scrollRef} style={{ overflowY: "auto", flex: 1, padding: "24px 26px 60px" }}>
          <div style={{ maxWidth: 760 }}>
            {floors.length === 0 ? (
              <div style={{ display: "grid", placeItems: "center", minHeight: 280, border: "1px dashed var(--line)",
                color: "var(--ink-faint)", textAlign: "center", padding: 30 }}>
                <div>
                  <Icon name="search" size={26} style={{ marginBottom: 12, opacity: .6 }} />
                  <div style={{ fontSize: 13 }}>No {filter.toLowerCase()} events in the log yet.</div>
                </div>
              </div>
            ) : floors.map((f, i) => (
              <div key={f.n} style={{ marginBottom: i === floors.length - 1 ? 0 : 30 }}>
                <FloorBand floor={f} />
              </div>
            ))}
            {/* the floor that hasn't happened yet */}
            {filter === "ALL" && (
              <div style={{ position: "relative", paddingLeft: 40, marginTop: 8, opacity: .5 }}>
                <span aria-hidden style={{ position: "absolute", left: 13, top: 3, width: 13, height: 13, transform: "translateX(-50%)",
                  borderRadius: "50%", border: "2px dashed var(--line-strong)", background: "var(--bg)" }} />
                <div style={{ fontFamily: "var(--font-mono)", fontSize: 10.5, letterSpacing: ".14em", textTransform: "uppercase", color: "var(--ink-faint)" }}>
                  Floor 10 — The Iron Tangle · not yet reached
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

/* ============================ console shell ============================ */
const NAV = [
  { group: "DM Console", items: [
    { icon: "review", label: "Review Queue", badge: CAMPAIGN.pending },
    { icon: "graph", label: "World Graph" },
    { icon: "clock", label: "Crawl Timeline", active: true },
    { icon: "studio", label: "Persona Studio" },
    { icon: "sim", label: "Simulation" },
  ]},
  { group: "Player-facing", items: [
    { icon: "crawler", label: "Crawler Interface" },
  ]},
];

function Shell() {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "232px 1fr", gridTemplateRows: "52px 1fr",
      gridTemplateAreas: '"brand topbar" "nav main"', height: "100%" }}>
      {/* brand */}
      <div style={{ gridArea: "brand", background: "var(--bg-1)", borderRight: "1px solid var(--line)",
        borderBottom: "1px solid var(--line)", display: "flex", alignItems: "center", gap: 11, padding: "0 18px" }}>
        <span style={{ width: 26, height: 26, display: "grid", placeItems: "center", border: "1.5px solid var(--accent)",
          color: "var(--accent)", fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 16 }}>C</span>
        <span style={{ fontFamily: "var(--font-display)", fontWeight: 600, fontSize: 15, letterSpacing: ".01em" }}>CrawlDirector</span>
      </div>

      {/* topbar */}
      <div style={{ gridArea: "topbar", background: "var(--bg-1)", borderBottom: "1px solid var(--line)",
        display: "flex", alignItems: "center", gap: 16, padding: "0 20px" }}>
        <button style={{ display: "inline-flex", alignItems: "center", gap: 9, padding: "6px 11px", background: "var(--bg-3)",
          border: "1px solid var(--line-strong)", fontSize: 12.5 }}>
          <span style={{ fontFamily: "var(--font-display)", fontWeight: 600 }}>{CAMPAIGN.name}</span>
          <Icon name="chevronDown" size={14} style={{ color: "var(--ink-faint)" }} />
        </button>
        <button style={{ display: "inline-flex", alignItems: "center", gap: 9, flex: 1, maxWidth: 380, padding: "7px 12px",
          background: "var(--bg)", border: "1px solid var(--line)", color: "var(--ink-faint)", fontSize: 12 }}>
          <Icon name="search" size={14} /><span>Search · Ask the Campaign</span>
          <span className="mono" style={{ marginLeft: "auto", fontSize: 10, color: "var(--ink-faint)" }}>⌘K</span>
        </button>
        <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 14 }}>
          <span style={{ display: "inline-flex", alignItems: "center", gap: 7, color: "var(--hot)", whiteSpace: "nowrap", fontFamily: "var(--font-mono)",
            fontSize: 10, letterSpacing: ".14em", textTransform: "uppercase" }}><span className="live-dot" />On air</span>
          <span style={{ width: 28, height: 28, borderRadius: "50%", background: "var(--bg-3)", border: "1px solid var(--line-strong)",
            display: "grid", placeItems: "center", fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--ink-dim)" }}>TR</span>
        </div>
      </div>

      {/* nav */}
      <nav style={{ gridArea: "nav", background: "var(--bg-1)", borderRight: "1px solid var(--line)", overflowY: "auto", padding: "14px 0" }}>
        {NAV.map((grp) => (
          <div key={grp.group} style={{ marginBottom: 18 }}>
            <div style={{ fontFamily: "var(--font-mono)", fontSize: 9, letterSpacing: ".18em", textTransform: "uppercase",
              color: "var(--ink-faint)", padding: "0 18px 8px" }}>{grp.group}</div>
            {grp.items.map((it) => (
              <button key={it.label} style={{ display: "flex", alignItems: "center", gap: 11, width: "100%", textAlign: "left",
                padding: "9px 18px", background: it.active ? "var(--bg-3)" : "transparent",
                borderLeft: `2px solid ${it.active ? "var(--accent)" : "transparent"}`, border: "none",
                borderLeftWidth: 2, borderLeftStyle: "solid", borderLeftColor: it.active ? "var(--accent)" : "transparent",
                color: it.active ? "var(--ink)" : "var(--ink-dim)", fontSize: 13 }}>
                <Icon name={it.icon} size={17} style={{ color: it.active ? "var(--accent)" : "var(--ink-faint)" }} />
                <span style={{ fontWeight: it.active ? 600 : 400 }}>{it.label}</span>
                {it.badge ? <span style={{ marginLeft: "auto", fontFamily: "var(--font-mono)", fontSize: 10, padding: "1px 6px",
                  background: "color-mix(in srgb, var(--accent) 16%, transparent)", color: "var(--accent)",
                  border: "1px solid color-mix(in srgb, var(--accent) 40%, transparent)" }}>{it.badge}</span> : null}
              </button>
            ))}
          </div>
        ))}
      </nav>

      {/* main */}
      <main style={{ gridArea: "main", overflow: "hidden", position: "relative", background: "var(--bg)", minWidth: 0 }}>
        <TimelineScreen />
      </main>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<Shell />);
